---
title: "Research_Paper_Code"
author: "aaron till"
date: "5/24/2018"
output: github_document
--- 

```{r installing packages}

library(rgdal)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(raster)



```

```{r parameters}

input_path = '/home/aatill/MME_Climate_Change_Research/Input_Data/'

```





```{r uploading and editing MME data}
setwd(input_path)

MME_raw <-read.csv("Fish Kill Data Updated 10_24_2018.csv")

MME_filtered <- MME_raw %>%
  filter(Min.Kill.Size!="Excludable") %>%
  dplyr::select(-contains('County'), -contains('Station.Name'), -contains('Cause.Desc'), -contains('Site.Seq.No'), -contains('Fishkill.Inv.Seq.No'), - contains('Location.QA.Comment'), -contains('Activity.Desc'), -contains('Recommended.Action.Desc'), -contains('Fish.Kill.Comment'), -contains('Live.Fish.Desc')) %>%
  mutate(Month = Investigation.Start.Month) %>%
  dplyr::select(-contains('Investigation.Start.Month'))

```




```{r uploading Thermal/NHD data and transforming Thermal}
setwd(input_path)


Thermal_Metrics <-read.csv("thermal_metrics.csv") 


NHD_WBIC <-read.csv("NHD_WBIC.csv")

Thermal_Metrics<- merge(Thermal_Metrics, NHD_WBIC) 
```




```{r tidying Thermal data}
Thermal_Tidy <- Thermal_Metrics%>%
  dplyr::select(-contains('jas')) %>%
  gather(key="type", value="temperature", starts_with('mean_surf_'),starts_with('mean_bot_'), starts_with('max_surf_'), starts_with('max_bot_')) %>%
  separate(type, into=c('metric', 'depth', 'Month'), sep='_')
  
  
Thermal_Tidy$Month <- str_to_title((Thermal_Tidy$Month)) 


  

```

```{r combining the datasets limited}

MME_With_Thermal <- merge(MME_filtered,Thermal_Tidy, all = FALSE) 

MME_With_Thermal <- distinct(MME_With_Thermal)

```

```{r full combined_data}


combined_data <-merge(MME_With_Thermal,Thermal_Tidy, all = TRUE) 

combined_data <- distinct(combined_data)

```

```{r setting up MME distinction and making dates}

combined_data$MME <-as.factor(ifelse(is.na(combined_data$Min.Kill.Size), 0, 1))

combined_data$Date <- make_date(year=combined_data$Year, month = combined_data$Month)

combined_data$Summerkill <- ifelse(combined_data$Cause.Category.4 == 'SUMMERKILL' & !is.na(combined_data$Cause.Category.4), 1, 0)
combined_data$winterkill <- ifelse(combined_data$Cause.Category.4 == 'WINTERKILL' & !is.na(combined_data$Cause.Category.4), 1, 0)
combined_data$Infection <- ifelse(combined_data$Cause.Category.4 == 'INFECTIOUS AGENT'& !is.na(combined_data$Cause.Category.4), 1, 0)
combined_data$Anthropogenic <- ifelse(combined_data$Cause.Category.4 == 'ANTHROPOGENIC CONDITION'& !is.na(combined_data$Cause.Category.4), 1, 0)


```

```{r creating restriction and zscores in combined_data_restricted}

combined_data_restricted <-combined_data%>%
  filter(Year>2003& Date < '2014-05-01')


combined_data_restricted$zscore_peak_temp <- (combined_data_restricted$peak_temp - ave(combined_data_restricted$peak_temp,combined_data_restricted$site_id)) / sd(combined_data_restricted$peak_temp)

combined_data_restricted<- combined_data_restricted %>%
  group_by(metric, depth, Month) %>%
  mutate(zscore_temp = (temperature - ave(temperature, site_id))/ sd(temperature)) %>%
  ungroup(metric, depth, Month)



```

```{r functions for accessing combined_data_restricted}

mean_surf <- function(data) {
  data %>%
    filter(metric=='mean', depth=='surf')
}
mean_bot <- function(data) {
  data %>%
    filter(metric=='mean', depth=='bot')
}
max_surf <- function(data) {
  data %>%
    filter(metric=='max', depth=='surf')
}
max_bot <- function(data) {
  data %>%
    filter(metric=='max', depth=='bot')
}
```


```{r tidying for main data pre spatial prt 1}

main_data_spread <- combined_data_restricted %>%
  mutate(type = paste(combined_data_restricted$metric,'_', combined_data_restricted$depth, sep = '')) %>%
  mutate(typeZ = paste(type, 'Z', sep = '')) %>%
  dplyr::select(-metric, -depth) %>%
  distinct() %>%
  spread(key = type, value = temperature) %>%
  spread(key = typeZ, value = zscore_temp)

```

```{r  tidying for main data pre spatial prt 2}

main_data_no_spatial <- main_data_spread %>%
  group_by(WBIC, site_id, Month, Year, peak_temp) %>%
  summarise(MME = max(as.numeric(MME))-1, Ice_Duration = mean(ice_duration_days, na.rm = TRUE), Schmidt = mean(schmidt_daily_annual_sum, na.rm = TRUE), Variance_After_Ice_30 = mean(coef_var_0.30, na.rm = TRUE), Variance_After_Ice_60 = mean(coef_var_30.60, na.rm = TRUE), Cumulative_Above_0 = mean(gdd_wtr_0c, na.rm = TRUE), Cumulative_Above_5 = mean(gdd_wtr_5c, na.rm = TRUE), Cumulative_Above_10 = mean(gdd_wtr_10c, na.rm = TRUE), Mean_Surf_Temp = max(mean_surf, na.rm = TRUE), Max_Surf_Temp = max(max_surf, na.rm = TRUE), Mean_Bot_Temp = max(mean_bot, na.rm = TRUE), Max_Bot_Temp = max(max_bot, na.rm = TRUE), Mean_Surf_Zscore = max(mean_surfZ, na.rm = TRUE), Max_Surf_Zscore = max(max_surfZ, na.rm = TRUE), Mean_Bot_Zscore = max(mean_botZ, na.rm = TRUE), Max_Bot_Zscore = max(max_botZ, na.rm = TRUE), Summerkill = max(Summerkill, na.rm = TRUE), Winterkill = max(winterkill, na.rm = TRUE), Infection = max(Infection, na.rm = TRUE), Anthropogenic = max(Anthropogenic, na.rm = TRUE)) %>%
  ungroup() 
```

```{r main data additional variables}

main_data_no_spatial$layer_dif <- main_data_no_spatial$Mean_Surf_Temp - main_data_no_spatial$Mean_Bot_Temp
main_data_no_spatial$quadratic_temp <- main_data_no_spatial$Mean_Surf_Temp^2 
main_data_no_spatial$Spring <- ifelse(main_data_no_spatial$Month == 'Mar' | main_data_no_spatial$Month == 'Apr' | main_data_no_spatial$Month == 'May', 1, 0)
```




#MAPPING DATA

```{r importing spatial data}

setwd(input_path)


dsn <- "lake_shapes"
ogrListLayers(dsn)
spatial <- readOGR(dsn, layer = 'model_lakes')

```

```{r making data frames from spatial data}

spatial_frame <- cbind(as.data.frame(spatial), as.data.frame(coordinates(spatial)))

```


```{r Merging with main data}

main_data <- merge(spatial_frame, main_data_no_spatial, all = FALSE)

```



```{r Creating Seasons}

main_data$Season <- main_data$Month

main_data$Season <- ifelse(main_data$Month =='Apr'| main_data$Month =='May', 'Spring', main_data$Season)



main_data$Season <- ifelse(main_data$Month =='Mar'| main_data$Month =='Dec'| main_data$Month =='Jan'| main_data$Month =='Feb', 'Winter', main_data$Season)


main_data$Season <- ifelse(main_data$Month =='Sep'|main_data$Month =='Jun'| main_data$Month =='Jul'| main_data$Month =='Aug', 'Summer', main_data$Season)


main_data$Season <- ifelse(main_data$Month =='Oct'| main_data$Month =='Nov', 'Fall', main_data$Season)


main_data$Season <-factor(main_data$Season, levels=c('Summer', 'Spring', 'Winter', 'Fall'))

```



# Outline of wisconsin shapefile data



```{r importing spatial data}

setwd(input_path)


dsn2 <- "wisconsin_outline"
ogrListLayers(dsn2)
spatial_w <- readOGR(dsn2, layer = 'wisco_only')

```


# Wisconsin Population Data from 2010 census data blocks

https://www.census.gov/geo/maps-data/data/tiger-data.html

```{r importing spatial data}

setwd(input_path)


dsn3 <- "census_data"
ogrListLayers(dsn3)

census_w <- readOGR(dsn3, layer = 'tabblock2010_55_pophu')
```

```{r}
census_w_coords <-  as.data.frame(coordinates(census_w))
census_w_pop <- dplyr::select(as.data.frame(census_w), 'POP10')
census_w_frame <- cbind(census_w_pop, census_w_coords)

```

``{r}
ggmap(Wisconsin_map) +
  geom_point(census_w_frame, aes(x = V1, y = V2))

``


```{r limiting size of coordinates}

main_data$long_round <- round(main_data$V1, 1)
main_data$lat_round <- round(main_data$V2, 1)
census_w_frame$long_round <- round(census_w_frame$V1, 1)
census_w_frame$lat_round <- round(census_w_frame$V2, 1)


```

```{r aggregate population by coordinates}

census_w_frame_summary <- census_w_frame %>%
  group_by(long_round, lat_round) %>%
  summarise(population = sum(POP10))

```

```{r}

main_data_census <- merge(main_data, census_w_frame_summary, full = TRUE) 
```




# Future Data


```{r}

setwd(input_path)


raw_future_CSIRO <- read_tsv('ACCESS_thermal_metrics.tsv')

```

```{r tidying and converting for predictive data}
raw_future_CSIRO <- merge(raw_future_CSIRO, NHD_WBIC)

future_untidied <- raw_future_CSIRO%>%
  dplyr::select(-contains('jas')) %>%
  gather(key="type", value="temperature", starts_with('mean_surf_'),starts_with('mean_bot_'), starts_with('max_surf_'), starts_with('max_bot_')) %>%
  separate(type, into=c('metric', 'depth', 'Month'), sep='_')
  
  
future_untidied$Month <- str_to_title((future_untidied$Month)) 


```

```{r tidy 1}

future_gathered <- future_untidied %>%
  group_by(metric, depth, Month) %>%
  mutate(zscore_temp = (temperature - ave(temperature, site_id))/ sd(temperature)) %>%
  ungroup(metric, depth, Month)

#future_gathered <- future_gathered %>% #Remove this line to compare concurrent forecasting with reality
 # filter(year >= 2041)

```

```{r tidy 2}
future_spread <- future_gathered %>%
  mutate(type = paste(future_gathered$metric,'_', future_gathered$depth, sep = '')) %>% 
  mutate(typeZ = paste(type, 'Z', sep = '')) %>%
  dplyr::select(-metric, -depth) %>%
  distinct() %>%
  spread(key = type, value = temperature) %>%
  spread(key = typeZ, value = zscore_temp)


```


```{r tidying 3}

future_data <- future_spread %>%
  group_by(WBIC, site_id, Month, year, peak_temp) %>% 
  summarise(Ice_Duration = mean(ice_duration_days, na.rm = TRUE), Schmidt = mean(schmidt_daily_annual_sum, na.rm = TRUE), Variance_After_Ice_30 = mean(coef_var_0.30, na.rm = TRUE), Variance_After_Ice_60 = mean(coef_var_30.60, na.rm = TRUE), Cumulative_Above_0 = mean(gdd_wtr_0c, na.rm = TRUE), Cumulative_Above_5 = mean(gdd_wtr_5c, na.rm = TRUE), Cumulative_Above_10 = mean(gdd_wtr_10c, na.rm = TRUE), Mean_Surf_Temp = max(mean_surf, na.rm = TRUE), Max_Surf_Temp = max(max_surf, na.rm = TRUE), Mean_Bot_Temp = max(mean_bot, na.rm = TRUE), Max_Bot_Temp = max(max_bot, na.rm = TRUE), Mean_Surf_Zscore = max(mean_surfZ, na.rm = TRUE), Max_Surf_Zscore = max(max_surfZ, na.rm = TRUE), Mean_Bot_Zscore = max(mean_botZ, na.rm = TRUE), Max_Bot_Zscore = max(max_botZ, na.rm = TRUE)) %>%
  ungroup() 
```

```{r main data additional variables}

future_data$Year <- future_data$year
future_data$layer_dif <- future_data$Mean_Surf_Temp - future_data$Mean_Bot_Temp
future_data$quadratic_temp <- future_data$Mean_Surf_Temp^2 
future_data$Spring <- ifelse(future_data$Month == 'Mar' | future_data$Month == 'Apr' | future_data$Month == 'May', 1, 0)
```



```{r Creating Seasons}

future_data$Season <- future_data$Month

future_data$Season <- ifelse(future_data$Month =='Apr'| future_data$Month =='May', 'Spring', future_data$Season)



future_data$Season <- ifelse(future_data$Month =='Mar'| future_data$Month =='Dec'| future_data$Month =='Jan'| future_data$Month =='Feb', 'Winter', future_data$Season)


future_data$Season <- ifelse(future_data$Month =='Sep'|future_data$Month =='Jun'| future_data$Month =='Jul'| future_data$Month =='Aug', 'Summer', future_data$Season)


future_data$Season <- ifelse(future_data$Month =='Oct'| future_data$Month =='Nov', 'Fall', future_data$Season)


future_data$Season <-factor(future_data$Season, levels=c('Summer', 'Spring', 'Winter', 'Fall'))

```

```{r spatial future}
future_data <- merge(spatial_frame, future_data, all = FALSE)


```


```{r future coordinate rounding and merging with census data}

future_data$long_round <- round(future_data$V1, 1)
future_data$lat_round <- round(future_data$V2, 1)

future_data_census <- merge(future_data, census_w_frame_summary, full = TRUE) 
```


# Snowfall Data



``{r}


  
tidy_snow <- function(data_input, year, month) {
  
  e <-extent(-92.9, -87, 42.4 , 46.9)
  a <- crop(raster(data_input),e)
  
  a1 <- as.data.frame(coordinates(a))
  a2<- as.data.frame(a)
  
  data <- na.omit(cbind(a1, a2)) 
   
  names(data) <- c('x', 'y', 'snow')

  data$long_round <- round(data$x, 1)
  data$lat_round <- round(data$y, 1)  

  data_output <- data %>%
  group_by(long_round, lat_round) %>%
  summarise(Snow = mean(snow))
    
  
  data_output$Year <- year
  data_output$Month <- month
  return(data_output)

}


```


``{r}

setwd('/home/aatill/Till_Thesis/Summer_Research_Work/MME_Climate_Change_Research/Input_Data/Prism Data/PRISM_Precip/')

snow_data <- rbind(tidy_snow('2004/PRISM_ppt_stable_4kmM3_200401_asc.asc',2004, 'Jan'),
                        tidy_snow('2004/PRISM_ppt_stable_4kmM3_200402_asc.asc', 2004, 'Feb'),
                        tidy_snow('2004/PRISM_ppt_stable_4kmM3_200412_asc.asc', 2004, 'Dec'),
                        tidy_snow('2005/PRISM_ppt_stable_4kmM3_200501_asc.asc', 2005, 'Jan'),
                        tidy_snow('2005/PRISM_ppt_stable_4kmM3_200502_asc.asc', 2005, 'Feb'),
                        tidy_snow('2005/PRISM_ppt_stable_4kmM3_200512_asc.asc', 2005, 'Dec'),
                        tidy_snow('2006/PRISM_ppt_stable_4kmM3_200601_asc.asc', 2006, 'Jan'),
                        tidy_snow('2006/PRISM_ppt_stable_4kmM3_200602_asc.asc', 2006, 'Feb'),
                        tidy_snow('2006/PRISM_ppt_stable_4kmM3_200612_asc.asc', 2006, 'Dec'),
                        tidy_snow('2007/PRISM_ppt_stable_4kmM3_200701_asc.asc', 2007, 'Jan'),
                        tidy_snow('2007/PRISM_ppt_stable_4kmM3_200702_asc.asc', 2007, 'Feb'),
                        tidy_snow('2007/PRISM_ppt_stable_4kmM3_200712_asc.asc', 2007, 'Dec'),
                        tidy_snow('2008/PRISM_ppt_stable_4kmM3_200801_asc.asc', 2008, 'Jan'),
                        tidy_snow('2008/PRISM_ppt_stable_4kmM3_200802_asc.asc', 2008, 'Feb'),
                        tidy_snow('2008/PRISM_ppt_stable_4kmM3_200812_asc.asc', 2008, 'Dec'),
                        tidy_snow('2009/PRISM_ppt_stable_4kmM3_200901_asc.asc', 2009, 'Jan'),
                        tidy_snow('2009/PRISM_ppt_stable_4kmM3_200902_asc.asc', 2009, 'Feb'),
                        tidy_snow('2009/PRISM_ppt_stable_4kmM3_200912_asc.asc', 2009, 'Dec'),
                        tidy_snow('2010/PRISM_ppt_stable_4kmM3_201001_asc.asc', 2010, 'Jan'),
                        tidy_snow('2010/PRISM_ppt_stable_4kmM3_201002_asc.asc', 2010, 'Feb'),
                        tidy_snow('2010/PRISM_ppt_stable_4kmM3_201012_asc.asc', 2010, 'Dec'),
                        tidy_snow('2011/PRISM_ppt_stable_4kmM3_201101_asc.asc', 2011, 'Jan'),
                        tidy_snow('2011/PRISM_ppt_stable_4kmM3_201102_asc.asc', 2011, 'Feb'),
                        tidy_snow('2011/PRISM_ppt_stable_4kmM3_201112_asc.asc', 2011, 'Dec'),
                        tidy_snow('2012/PRISM_ppt_stable_4kmM3_201201_asc.asc', 2012, 'Jan'),
                        tidy_snow('2012/PRISM_ppt_stable_4kmM3_201202_asc.asc', 2012, 'Feb'), 
                        tidy_snow('2012/PRISM_ppt_stable_4kmM3_201212_asc.asc', 2012, 'Dec'),
                        tidy_snow('2013/PRISM_ppt_stable_4kmM3_201301_asc.asc', 2013, 'Jan'),
                        tidy_snow('2013/PRISM_ppt_stable_4kmM3_201302_asc.asc', 2013, 'Feb'), 
                        tidy_snow('2013/PRISM_ppt_stable_4kmM3_201312_asc.asc', 2013, 'Dec'))


```





