---
title: "Supplementary Information"
author: "aaron till"
date: "6/18/2018"
output: html_document
---

```{r Infectious Agent Yearly Test}


combined_data_restricted <- combined_data_restricted %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 == 'INFECTIOUS AGENT'), 'Infectious Agent'))  %>%
    mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 == 'ANTHROPOGENIC CONDITION'), 'Human Perturbation'))%>%
    mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 == 'WINTERKILL'), 'Winterkill'))

combined_data_restricted$sig_all <- ifelse(combined_data_restricted$Cause.Category.4 == 'Winterkill', 'p<.05', 'p>.05')
combined_data_restricted$sig_all <- factor(combined_data_restricted$sig_all, levels = c('p>.05', 'p<.05'))

ultimate_zscore_boxplot <- mean_surf(combined_data_restricted) %>%
  filter(Cause.Category.4 == 'Infectious Agent' | Cause.Category.4 == 'Winterkill' | Cause.Category.4 == 'Human Perturbation' ) %>%
ggplot(aes(y = zscore_temp,x = Cause.Category.4)) +
  theme_tufte() +
  ylab('Z-score All Seasons')+
  xlab('Category of Killtype')+
  xlab(NULL) +
  geom_hline(yintercept = 0, alpha = 0.5) +
  theme(text = element_text(size=13),axis.text = element_text(size=13),
        axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+
  geom_boxplot(outlier.alpha = 0.1,aes(fill = sig_all)) + 
  scale_fill_manual(values = c('grey', 'gold'), guide = guide_legend(title = NULL))

ultimate_zscore_boxplot


ttest_data_all_anthro <- filter(mean_surf(combined_data_restricted), Cause.Category.4 == 'Human Perturbation')
t.test(ttest_data_all_anthro$zscore_temp, mu = 0)

ttest_data_infectious_all<- filter(mean_surf(combined_data_restricted), Cause.Category.4 == 'Infectious Agent')
t.test(ttest_data_infectious_all$zscore_temp, mu = 0)

ttest_data_all <- filter(mean_surf(combined_data_restricted), Cause.Category.4 == 'Winterkill')
t.test(ttest_data_all$zscore_temp, mu = 0)


```

```{r ice duration winterkill}

combined_data_restricted <- combined_data_restricted %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(is.na(Cause.Category.4)), 'Summer Non-event'))

combined_data_restricted_winter <- combined_data_restricted %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 == 'Summer Non-event'), 'Winter Non-event')) %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 == 'WINTERKILL'), 'Winterkill')) 

combined_data_restricted_winter$sig_ice <- ifelse(combined_data_restricted_winter$Cause.Category.4 == 'Winterkill', 'p<.05', 'p>.05')
combined_data_restricted_winter$sig_ice <- factor(combined_data_restricted_winter$sig_ice, levels = c('p>.05', 'p<.05'))

ice_duration_boxplot <- mean_surf(combined_data_restricted_winter) %>%
  filter(Month == 'Jan' | Month == 'Feb' | Month == 'Dec' | Month == 'Mar') %>%
  filter(Cause.Category.4 == 'Winterkill' | Cause.Category.4 == 'Winter Non-event' ) %>%
ggplot(aes(y = ice_duration_days,x = Cause.Category.4)) +
  theme_tufte() +
  ylab('Ice Duration (Days)')+
  xlab('Category of Killtype')+
  xlab(NULL) +
    theme(text = element_text(size=13),axis.text = element_text(size=13),
          axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+
  geom_boxplot(outlier.alpha = 0.1, aes(fill = sig_ice)) + 
  scale_fill_manual(values = c('grey', 'gold'), guide = guide_legend(title = NULL))

ice_duration_boxplot

ice_anova_data <- mean_surf(combined_data_restricted_winter) %>%
  filter(Month == 'Jan' | Month == 'Feb' | Month == 'Dec' | Month == 'Mar') %>%
  filter(Cause.Category.4 == 'Winterkill' | Cause.Category.4 == 'Winter Non-event')

anova_ice <- aov(ice_duration_days ~ Cause.Category.4, ice_anova_data)
summary(anova_ice)
tuk <- TukeyHSD(anova_ice)
tuk

```

```{r snowfall winterkill}

snowfall <- merge(main_data_census, snow_data)

snowfall$sig_ice <- ifelse(snowfall$Winterkill == 1, 'p>.05', 'p>.05')

snowfall$sig_ice <- factor(snowfall$sig_ice, levels = c('p>.05', 'p<.05'))

snow_boxplot <- snowfall %>%
  filter(Month == 'Jan' | Month == 'Feb' | Month == 'Dec') %>%
  filter(Winterkill == 1 | MME == 0 ) %>%
ggplot(aes(y =Snow,x = factor(Winterkill))) +
  theme_tufte() +
  ylab('Precipitation')+
  xlab('Winterkill')+
  geom_boxplot(outlier.alpha = 0.1, aes(fill = sig_ice)) + 
  theme(text = element_text(size=13),axis.text = element_text(size=13),
        axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+
  scale_fill_manual(values = c('grey', 'gold'), guide = guide_legend(title = NULL))

snow_boxplot

snow_anova_data <- snowfall %>%
  filter(Month == 'Jan' | Month == 'Feb' | Month == 'Dec') %>%
  filter(Winterkill == 1 |MME == 0)

anova_snow <- aov(Snow ~ factor(Winterkill), snow_anova_data)
summary(anova_snow)
tuk <- TukeyHSD(anova_snow)
tuk
```




# MME Distribution

```{r}

main_data$Month = factor(main_data$Month, levels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", 'Oct', "Nov", "Dec"))  

plot1<-ggplot(filter(main_data, MME ==1),aes(x=factor(Year), fill=Month)) +
  stat_count()+
  #geom_boxplot(color="black",aes(y=peak_temp, group=Year)) +
  ylab("")+
  xlab("Year") +
  ggtitle("Number Of Events Per Year")+              #Peak Temperatures Per Year")+
  scale_x_discrete()+
  #guides(fill=FALSE) +
  theme_tufte()
  #scale_fill_brewer(palette = 'matlab.like', direction = -1)
plot1

#number of events per month

plot1.1<-ggplot(filter(main_data, MME == 1),aes(x=Month, fill=Month)) +
  stat_count()+
  xlab("Month")+
  ylab("")+
  ggtitle("Number Of Events Per Month")+
  scale_x_discrete() +
  guides(fill=FALSE) +
  theme_tufte()
  #scale_fill_brewer()
plot1.1

grid.arrange(plot1, plot1.1)




```

```{r}

main_data %>%
  filter(MME == 1) %>%
  group_by(WBIC) %>%
  summarise(n = n()) %>%
ggplot(aes(x = n)) +
  geom_bar() +
  ylab('Number of Lakes')+
  xlab('Number of Events') +
  theme_tufte()


```


```{r}


Wi_Lakes_Maps <- read_excel("Input_Data/Wi_Lakes_Maps.xlsx")
MME_data <- read_csv("Input_Data/Fish Kill Data Updated 10_24_2018.csv") %>%       filter(Min.Kill.Size!="Excludable") %>%
  dplyr::select(-contains('County'), -contains('Station.Name'), -contains('Cause.Desc'), -contains('Site.Seq.No'), -contains('Fishkill.Inv.Seq.No'), - contains('Location.QA.Comment'), -contains('Activity.Desc'), -contains('Recommended.Action.Desc'), -contains('Fish.Kill.Comment'), -contains('Live.Fish.Desc')) %>%
  mutate(Month = Investigation.Start.Month) %>%
  dplyr::select(-contains('Investigation.Start.Month'))

depth_data <- Wi_Lakes_Maps %>% left_join(MME_data, By = WBIC) %>% mutate(MME = ifelse(is.na(Investigation.Start.Date), 0, 1))


depth_data %>%
  filter(!is.na(OFFICIAL_MAX_DEPTH_VALUE)) %>%
  filter(!is.na(MME)) %>%
  group_by(WBIC) %>%
  summarise(Depth = mean(as.numeric(OFFICIAL_MAX_DEPTH_VALUE)), MME = sum(MME)) %>%
  mutate(MME = ifelse(MME >= 4, '4+', MME)) %>%
ggplot(aes(x=WBIC, y = Depth, color = factor(MME))) +
  geom_point()+
  facet_grid(.~MME) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

depth_data %>%
  filter(!is.na(OFFICIAL_MAX_DEPTH_VALUE)) %>%
  filter(!is.na(MME)) %>%
  group_by(WBIC) %>%
  summarise(Depth = mean(as.numeric(OFFICIAL_MAX_DEPTH_VALUE)), Dieoffs = sum(MME))%>%
  mutate(Dieoffs = ifelse(Dieoffs >= 4, '4+', Dieoffs)) %>%
ggplot(aes(x=Dieoffs, y = Depth, colour = Dieoffs)) +
  geom_boxplot(aes(group = Dieoffs))+
  guides(colour = FALSE)+
  theme_tufte()


anova_depth <- aov(Depth ~ factor(MME), depth_data %>%
  filter(!is.na(OFFICIAL_MAX_DEPTH_VALUE)) %>%
  filter(!is.na(MME)) %>%
  group_by(WBIC) %>%
  summarise(Depth = mean(as.numeric(OFFICIAL_MAX_DEPTH_VALUE)), MME = max(MME)))
summary(anova_depth)
tuk <- TukeyHSD(anova_depth)
tuk

```



```{r avg temp over time}

full_data <- lasso_coords_summer_predictions%>%
                        filter(Year > 2040 & Year < 2060) %>%
                        group_by(Year) %>%
                        summarise(Summerkills = sum(Prob), Temp = mean(Mean_Surf_Temp))
  
  #bind(lasso_coords_summer_predictions%>%
  #                      filter(Year > 2040) %>%
  #                      group_by(Year) %>%
  #                      summarise(Summerkills = sum(Prob), 
  #                            Temp = mean(Mean_Surf_Temp)),  
  #                main_data%>% 
  #                      group_by(Year) %>%
  #                      filter(Year<2014) %>%
  #                      summarise(Summerkills = sum(Summerkill), 
  #                      Temp = mean(Mean_Surf_Temp))
#) 

#full_data = full_data%>%bind_rows(tibble(Year = c(2015:2040, 2060:2080), Summerkills = NA, Temp = NA)) %>% mutate(y = 25)



plot <- full_data %>%
  ggplot(aes(x= Year, y = Temp)) + 
  geom_point() + 
  ylab('Average Yearly Surface Temperature')

plot




```


```{r}

main_data %>%
  filter(MME > 0) %>%
  filter(Season == 'Summer') %>%
  group_by(WBIC,Month, Year) %>%
  summarise(Mortality_Months = max(MME)) %>%
  group_by(Year, WBIC) %>%
  summarise(Mortality_Months = sum(Mortality_Months)) %>%
  ggplot(aes(x = factor(Mortality_Months))) +
    xlab('Multiple Mortalities in One Summer')+
    geom_bar()


```