---
title: "Visualization"
author: "aaron till"
date: "5/29/2018"
output: html_document
---

```{r}
library(ggplot2)
library(ggthemes)
library(ggmap)
library(gridExtra)
library(scales)
library(car)
library(DescTools)
library(spdep)

```





# Boxplot of killtype mean temps

```{r rerun combined_data_restricted before this if out of order and having problems}
combined_data_restricted <- combined_data_restricted %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(is.na(Cause.Category.4)), 'Summer Non-event')) %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 =='SUMMERKILL'), 'Summerkill')) %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 =='INFECTIOUS AGENT'), 'Infectious Agent'))



combined_data_restricted$sig <- ifelse(combined_data_restricted$Cause.Category.4 == 'Summerkill', 'p<.05', 'p>.05')
combined_data_restricted$sig <- factor(combined_data_restricted$sig, levels = c('p>.05', 'p<.05'))

boxplot1 <- mean_surf(combined_data_restricted) %>%
  filter(Month == 'Jul' | Month == 'Jun' | Month == 'Aug' | Month == 'Sep') %>%
  filter(Cause.Category.4 == 'Summerkill' | Cause.Category.4 == 'Summer Non-event' | Cause.Category.4 == 'Infectious Agent') %>%   
ggplot(aes(y = temperature,x = Cause.Category.4)) +
  theme_tufte() +  
  ylab('Mean Surf. Temp. (Celsius)')+
  theme(text = element_text(size=13),
    axis.text = element_text(size=13),
    legend.justification = c(1, 0), 
    legend.position = c(0.35, 0.25),
    legend.box.margin=margin(c(50,50,50,50)),
    axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"),
    axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  xlab(NULL)+
  geom_boxplot(outlier.alpha = 0.1, aes(fill = sig)) + 
  ggtitle('A') +
  scale_fill_manual(values = c('grey', 'gold'), guide = guide_legend(title = NULL))

boxplot2 <- mean_surf(combined_data_restricted) %>%
  filter(Month == 'Jul' | Month == 'Jun' | Month == 'Aug' | Month == 'Sep') %>%
  filter(Cause.Category.4 == 'Summerkill' | Cause.Category.4 == 'Infectious Agent' | Cause.Category.4 == 'Summer Non-event') %>%   
ggplot(aes(y = zscore_temp,x = Cause.Category.4)) +
  theme_tufte() +
  ylab('Z-score (Celsius)') +
  guides(fill = FALSE) +
  theme(text = element_text(size=13), 
        axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+
  geom_boxplot(outlier.alpha = 0.1, aes(fill = sig)) +
    theme(axis.text = element_text(size=13))+

  xlab(NULL) +
  geom_hline(yintercept = 0, alpha = 0.5)+ 
  ggtitle('C') +
  scale_fill_manual(values = c('grey', 'gold'), guide = guide_legend(title = 'T-test'))

grid.arrange(boxplot1, boxplot2)


```

```{r Summer Anova}

#make sure to run combined_dat_restricted and the above chunk before this or error will occure, not sure why

anova_data <- mean_surf(combined_data_restricted) %>% filter(Month == 'Jul' | Month == 'Jun' | Month == 'Aug' | Month == 'Sep') %>% filter((Cause.Category.4 == 'Infectious Agent' | Cause.Category.4 == 'Summerkill' | Cause.Category.4 == 'Summer Non-event'))



leveneTest(y = temperature ~ Cause.Category.4, data = anova_data, center = mean)
#cannot use ANOVA must use WELCH oneway.test

welch_cause_type <- oneway.test(temperature ~ Cause.Category.4, anova_data)
print(welch_cause_type)

DunnettTest(temperature ~ factor(Cause.Category.4), data = anova_data, control = 'Summer Non-event')
```
```{r summer Zscore Anova}
#leveneTest(y = zscore_temp ~ Cause.Category.4, data = anova_data)

#anova_zscore_cause_Type <- aov(zscore_temp ~ Cause.Category.4,anova_data)
#summary(anova_zscore_cause_Type)
#tuk <- TukeyHSD(anova_zscore_cause_Type)
#tuk

ttest_data_summerkill <- filter(anova_data, Cause.Category.4 == 'Summerkill')
t.test(ttest_data_summerkill$zscore_temp, mu = 0)


ttest_data_infectious_summer<- filter(anova_data, Cause.Category.4 == 'Infectious Agent')
t.test(ttest_data_infectious_summer$zscore_temp, mu = 0)

ttest_data_summer_nonevent<- filter(mean_surf(anova_data), Cause.Category.4 == 'Summer Non-event')
t.test(ttest_data_summer_nonevent$zscore_temp, mu = 0)

#number of above 0 zscore for summerkill
mean_surf(combined_data_restricted) %>% filter(Month == 'Jul' | Month == 'Jun' | Month == 'Aug' | Month == 'Sep') %>% filter(Cause.Category.4 == 'Summerkill') %>% group_by(zscore_temp > 0) %>% summarise(n())

```

```{r winterkill boxplots}
combined_data_restricted <- combined_data_restricted %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(is.na(Cause.Category.4)), 'Summer Non-event'))

combined_data_restricted_winter <- combined_data_restricted %>%
  mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 == 'Summer Non-event'), 'Winter Non-event'))  %>%
    mutate(Cause.Category.4 = replace(as.character(Cause.Category.4), which(Cause.Category.4 == 'WINTERKILL'), 'Winterkill'))

boxplot1_winter <- mean_surf(combined_data_restricted_winter) %>%
  filter(Month == 'Dec' | Month == 'Jan' | Month == 'Feb' | Month == 'Mar') %>%
  filter(Cause.Category.4 == 'Winterkill' | Cause.Category.4 == 'Winter Non-event') %>%
ggplot(aes(y = temperature,x = Cause.Category.4)) +
  theme_tufte() +
  ylab(NULL)+
  xlab(NULL)+
  theme(text = element_text(size=13), 
        axis.text = element_text(size = 13),
    axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"), 
    axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  geom_boxplot(outlier.alpha = 0.1, aes(fill = sig))+ 
  guides(fill = FALSE)+ 
  ggtitle('B') +
  scale_fill_manual(values = c('grey', 'gold'))

boxplot2_winter <- mean_surf(combined_data_restricted_winter) %>%
  filter(Month == 'Dec' | Month == 'Jan' | Month == 'Feb' | Month == 'Mar') %>%
  filter(Cause.Category.4 == 'Winterkill' | Cause.Category.4 == 'Winter Non-event') %>%   
ggplot(aes(y = zscore_temp,x = Cause.Category.4)) +
  theme_tufte() +
  xlab('Category of Killtype')+
  geom_boxplot(outlier.alpha = 0.1, aes(fill = sig)) +
  theme(text = element_text(size=13),
        axis.text = element_text(size = 13),
    axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+
  xlab(NULL) +
  ylab(NULL)+
  ylim(-2.5,2) +
  geom_hline(yintercept = 0, alpha = 0.5)+
  scale_fill_brewer()+ 
  guides(fill = FALSE)+ 
  ggtitle('D') +
  scale_fill_manual(values = c('grey', 'gold'))

grid.arrange(boxplot1_winter, boxplot2_winter)

```

```{r winterkill Anova }

anova_data_winter <- mean_surf(combined_data_restricted_winter) %>%  
  filter(Month == 'Dec' | Month == 'Jan' | Month == 'Feb' | Month == 'Mar') %>%
  filter(Cause.Category.4 == 'WINTERKILL' | Cause.Category.4 == 'WINTER NON-EVENT')    

leveneTest(y =temperature ~ Cause.Category.4, data = anova_data_winter, center = mean)


anova_cause_Type <- aov(temperature ~ Cause.Category.4, anova_data_winter)
summary(anova_cause_Type)
tuk <- TukeyHSD(anova_cause_Type)
tuk
```

```{r winter Zscore Anova }


#leveneTest(y =zscore_temp ~ Cause.Category.4, data = anova_data_winter, center = mean)

#anova_zscore_cause_Type <- aov(zscore_temp ~ Cause.Category.4,anova_data_winter)
#summary(anova_zscore_cause_Type)
#tuk <- TukeyHSD(anova_zscore_cause_Type)
#tuk

ttest_data_winter<- filter(anova_data_winter, Cause.Category.4 == 'WINTERKILL')
t.test(ttest_data_winter$zscore_temp, mu = 0)

ttest_data_winter_all<- filter(mean_surf(anova_data_winter), Cause.Category.4 == 'WINTER NON-EVENT')
t.test(ttest_data_winter_all$zscore_temp, mu = 0)


```

```{r ultimate boxplots}


#combined_data_restricted$Cause.Category.4 <- factor(combined_data_restricted$Cause.Category.4, levels = c('SUMMERKILL', 'NON-EVENT', 'INFECTIOUS AGENT', 'WINTERKILL', 'ANTHROPOGENIC CONDITION'))



xbox <- grid.arrange(boxplot1,boxplot1_winter,ncol = 2, widths = c(6, 3.6))
ybox <- grid.arrange(boxplot2,boxplot2_winter, ncol = 2, widths = c(6, 3.6))

grid.arrange(xbox, ybox)

ttest_winter <- filter(combined_data_restricted, Cause.Category.4 == 'ANTHROPOGENIC CONDITION' )
t.test(ttest_winter$zscore_temp, mu = 0) # There are a lot of cold lakes without winterkills...


```









# Final projected MME by year & season (include original MME data for concurrent)}





```{r New smoothed charts}


plot1<-main_data %>%
  group_by(Year) %>%
  filter(Year<2014) %>%
  summarise(Summerkill = sum(Summerkill), Temp = mean(Mean_Surf_Temp)) %>%
ggplot(aes(x=Year,y = Summerkill)) +
  geom_point(color='black')+
  #geom_smooth(span =0.5, se = FALSE, color ='black')+
  #geom_smooth(method = 'loess', size = 1)+
  #scale_x_discrete(limits= labels1) +
  #geom_boxplot(color="black",aes(y=peak_temp, group=Year)) +
  ylab("Total Observed Summerkills")+
  xlab(NULL) +
  guides(fill=FALSE) +
  theme_calc()+
  ylim(-30,110) +
  theme(axis.text.x=element_text(angle=90), 
        legend.position = 'left',
    text = element_text(size=13), 
    plot.title = element_text(margin = margin(b = -50))) +
  ggtitle('A') +
  scale_x_discrete( limits = c(2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014))
plot1

plot2<-lasso_coords_summer_predictions %>%
  filter(Year <2060 & Year > 2030) %>%  
  group_by(Year) %>%
  summarise('Total Kills' = sum(Prob))%>%
  #filter(Prob > 0.01) %>%
ggplot(aes(x=Year,y = `Total Kills`)) +
  geom_smooth(span =0.6, color ='black' )+
  #geom_smooth(method = 'loess', size = 1)+
  scale_x_discrete(limits= c(2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059) ) +
  ylab("Total Predicted Summerkills")+
  xlab(NULL) +
  #theme_tufte()+
  theme_calc()+
  ylim(-30,110) +
  ggtitle('B') +
  theme(axis.text.x=element_text(angle=90),
    text = element_text(size=13), plot.title = element_text(margin = margin(b = -50)))
plot2


plot3<-lasso_coords_summer_predictions %>%
  filter(Year >2060) %>%  
  group_by(Year) %>%
  summarise('Total Kills' = sum(Prob))%>%
  #filter(Prob > 0.01) %>%
ggplot(aes(x=Year,y = `Total Kills`)) +
  geom_smooth(span =0.6, color ='black' )+
  #geom_smooth(method = 'loess', size = 1)+
  scale_x_discrete(limits= c(2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099)) +
  ylab("Total Predicted Summerkills")+
  xlab(NULL) +
  #theme_tufte()+
  theme_calc()+
  ylim(-30,110) +
  ggtitle('B') +
  theme(axis.text.x=element_text(angle=90),
    text = element_text(size=13), plot.title = element_text(margin = margin(b = -50)))
plot3

grid.arrange(plot1,plot2,plot3, ncol = 3, widths = c(.6, 1, 1))


```


```{r one figure}
full_data <- bind(lasso_coords_summer_predictions%>%
                        filter(Year > 2002) %>%
                        group_by(Year) %>%
                        summarise(Summerkills = sum(Prob), 
                              Temp = mean(Mean_Surf_Temp)),  
                  main_data%>% 
                        group_by(Year) %>%
                        filter(Year<2014) %>%
                        summarise(Summerkills = sum(Summerkill), 
                        Temp = mean(Mean_Surf_Temp))
) 

full_data = full_data%>%bind_rows(tibble(Year = c(2015:2040, 2060:2080), Summerkills = NA, Temp = NA)) %>% mutate(y = 25)


plot<- full_data%>%
ggplot(aes(x=Year,y = Summerkills)) +
  geom_rect(xmin = 2014, xmax = 2041, ymin = 0, ymax = 110, alpha = 0.01)+
  geom_rect(xmin = 2059, xmax = 2081, ymin = 0, ymax = 110, alpha = 0.01)+
  geom_line(color = 'black')+
  #geom_smooth(span = 0.3, color = 'black', se = FALSE)+
  #geom_ribbon(ymin = lb, ymax = ub, alpha = 0.5) +
  geom_bar(stat = 'identity', aes(x = Year, y = y, fill = Temp), alpha = 0.5)+

  ylab("Total Predicted Summerkills")+
  xlab(NULL) +
  #theme_tufte()+
  theme_calc()+
  scale_fill_gradient(low = 'blue', high = 'red', limits = c(9, 16)) +
  #scale_fill_manual( palette = 'Blue-Red', limits = c(9, 16), breaks = waiver())+
  ylim(0,105) 

plot







```



```{r model summerkills to temperature}



plot2<-lasso_coords_summer_predictions %>%
  filter(Year > 2002) %>%
ggplot(aes(x=Mean_Surf_Temp,y = Prob)) +
  
  geom_smooth(span =0.6, color ='black' )+
  ylab("Probability of Summerkill")+
  xlab('Monthly Mean Surface Temperature') +
  #theme_tufte()+
  theme_calc()+
  ggtitle('D') +
  theme(
    text = element_text(size=13), plot.title = element_text(margin = margin(b = -50)))
plot2




```












```{r qualitative analysis}

main_data %>%
  group_by(Year) %>%
  summarise(Summerkill = sum(Summerkill), Temp = mean(Mean_Surf_Temp)) %>%
  arrange(desc(Summerkill))

main_data %>%
  filter(Summerkill == 1) %>%
  group_by(Year) %>%
  summarise(n = n()) %>%
  arrange(n)
  #mean = n() / 10


lasso_coords_summer_predictions %>%
  filter(Year <2060 & Year > 2030) %>%
  group_by(Year) %>%
  summarise(Summerkill = sum(Prob), Temp = mean(Mean_Surf_Temp)) %>%
  arrange(desc(Summerkill))

lasso_coords_summer_predictions %>%
  filter(Year <2060 & Year > 2030) %>%
  group_by(Year) %>%
  summarise(Summerkill = sum(Prob)) %>%
  arrange(Summerkill)
    #mean = Summerkill/19


lasso_coords_summer_predictions %>%
  filter(Year >2060) %>%
  group_by(Year) %>%
  summarise(Summerkill = sum(Prob), Temp = mean(Mean_Surf_Temp)) %>%
  arrange(desc(Summerkill))

lasso_coords_summer_predictions %>%
  filter(Year >2060) %>%
  group_by(Year) %>%
  summarise(Summerkill = sum(Prob)) %>%
  arrange(Summerkill)


```


# spatial mappings

```{r}

map_data_w <-fortify(spatial_w) 

bbox =c(-92.9, 42.4, -87, 46.9) 
Wisconsin_map <- get_map(bbox, zoom = 7, maptype = 'toner-lines')
ggmap(Wisconsin_map, darken = c(0,'black')) + 
    geom_path(data = map_data_w, aes(x = long, y = lat, group = group))# +


```


```{r concurrent maps}

plot(spatial_w)


  #merge(as.data.frame(spatial_w), as.data.frame(coordinates(spatial_w)))


MME_lakes_of_wisconsin <- ggmap(Wisconsin_map) +
  geom_point(data = filter(main_data, MME == 1), aes(x = V1, y = V2)) +
  #geom_polygon(data = map_data_w, aes(x = V1, y = V2)) +
  geom_path(data = map_data_w, aes(x = long, y = lat, group = group))+
  theme(text = element_text(size=13), plot.title = element_text(margin = margin(b = -50), hjust = 0.05)) +
  ggtitle('A')
          
          # +
  #coord_equal()
  #geom_point(data = as.data.frame(coordinates(spatial_w)), aes(x = V1, V2))


MME_lakes_of_wisconsin


```

```{r}
MME_lakes_of_wisconsin_dif_categories <- ggmap(Wisconsin_map) +
  geom_point(data = filter(main_data, MME == 1 & Summerkill == 1), aes(x = V1, V2), fill = 'red', shape = 21) +
  geom_point(data = filter(main_data, MME == 1 & Winterkill == 1), aes(x = V1, V2), fill = 'blue', shape = 21) +
  geom_point(data = filter(main_data, MME == 1 & Infection == 1), aes(x = V1, V2), fill = 'green', shape = 21) +
   geom_point(data = filter(main_data, MME == 1 & Anthropogenic == 1), aes(x = V1, V2), fill = 'orange', shape = 21)+
  theme(text = element_text(size=10), plot.title = element_text(margin = margin(b = -50), hjust = 0.05)) +
  ggtitle('A')

summarized_main_data<-main_data %>%
  group_by(WBIC) %>%
  summarise(MME = max(Summerkill), V1 = mean(V1), V2 = mean(V2))

color_seperated_lakes_of_wisconsin <- ggmap(Wisconsin_map) +
  geom_point(data = arrange(summarized_main_data, MME), aes(x = V1, V2, color = MME, alpha = MME), size = 0.5)+
  scale_color_gradient(low = 'Blue', high = 'Red', limits = c(0, 1)) +
  theme(axis.title.x=element_blank(),
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        axis.title.y=element_blank()
        #axis.text.y=element_blank(), 
        #axis.ticks.y=element_blank()
        ) +
    guides(color=FALSE, alpha = FALSE) +
    scale_alpha(limits = c(0,1))+

  geom_path(data = map_data_w, aes(x = long, y = lat, group = group))+
  #geom_point(data = filter(main_data, MME == 0), aes(x = V1, V2), fill = 'blue', shape = 21)+
  #geom_point(data = filter(main_data, MME == 1), aes(x = V1, V2), fill = 'red', shape = 21)
  theme(text = element_text(size=13), plot.title = element_text(margin = margin(b = -25), hjust = 0.02)) +
  ggtitle('A')
  
color_seperated_lakes_of_wisconsin

```


```{r future}

lasso_coords_summer_predictions$No_Event_Prob <- 1 - lasso_coords_summer_predictions$Prob

summarized_lasso_summer_predictions_p2 <- lasso_coords_summer_predictions %>%
  filter(Year > 2030 & Year < 2070) %>%
  group_by(WBIC) %>%
  summarise(Prob = (1 - prod(No_Event_Prob)), V1 = mean(V1), V2 = mean(V2)) 

summarized_lasso_summer_predictions_p3 <- lasso_coords_summer_predictions %>%
  filter(Year > 2070) %>%
  group_by(WBIC) %>%
  summarise(Prob = (1 - prod(No_Event_Prob)), V1 = mean(V1), V2 = mean(V2)) 

summarized_lasso_summer_predictions_both <- lasso_coords_summer_predictions %>%
  filter(Year > 2020) %>%
  group_by(WBIC) %>%
  summarise(Prob = (1 - prod(No_Event_Prob)), V1 = mean(V1), V2 = mean(V2)) 

logreg_at_risk_lakes_of_wisconsin_period_2 <- ggmap(Wisconsin_map) + 
  geom_point(data = arrange(summarized_lasso_summer_predictions_p2, Prob), aes(x = V1, V2, color = Prob, alpha = Prob), size = 0.5)+
  scale_color_gradient(low = 'Blue', high = 'Red',na.value = 'red', limits = c(0, 1)) +
    theme(axis.title.x=element_blank(),
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  guides(color=FALSE, alpha = FALSE) +
    scale_alpha(limits = c(0,1))+
  geom_path(data = map_data_w, aes(x = long, y = lat, group = group)) +
  theme(text = element_text(size=13), plot.title = element_text(margin = margin(b = -25), hjust = 0.02)) +
  ggtitle('B')
logreg_at_risk_lakes_of_wisconsin_period_2 


logreg_at_risk_lakes_of_wisconsin_period_3 <- ggmap(Wisconsin_map) + 
  geom_point(data = arrange(summarized_lasso_summer_predictions_p3, Prob), aes(x = V1, V2, color = Prob, alpha = Prob),size = 0.5)+
 scale_color_gradient(low = 'Blue', high = 'Red', na.value = 'Red', limits = c(0, 1)) +
    theme(axis.title.x=element_blank(),
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.key.size = unit(0.3, 'cm'), 
        legend.text= element_text(size = 5),
        legend.title = element_text(size = 10))+
  guides(alpha = FALSE) +
  scale_alpha(limits = c(0,1))+
  geom_path(data = map_data_w, aes(x = long, y = lat, group = group))+
  theme(text = element_text(size=13), plot.title = element_text(margin = margin(b = -25), hjust = 0.02)) +
  ggtitle('C')
logreg_at_risk_lakes_of_wisconsin_period_3 


```


```{r}


grid.arrange(color_seperated_lakes_of_wisconsin,logreg_at_risk_lakes_of_wisconsin_period_2, logreg_at_risk_lakes_of_wisconsin_period_3, ncol = 3, widths = c(1.07,1,1.3))


```

#spatial analysis


```{r}

coordinates(summarized_main_data) <- c('V1', 'V2')

coordinates(summarized_lasso_summer_predictions_p2) <- c('V1', 'V2')

coordinates(summarized_lasso_summer_predictions_p3) <- c('V1', 'V2')


```

```{r neighbors}


nb_p1 <- knn2nb(knearneigh(coordinates(summarized_main_data),longlat = TRUE, k = 2))
nb_p2 <- knn2nb(knearneigh(coordinates(summarized_lasso_summer_predictions_p2),longlat = TRUE, k = 2))
nb_p3 <- knn2nb(knearneigh(coordinates(summarized_lasso_summer_predictions_p3),longlat = TRUE, k = 2))

```


```{r weights}

weights_p1 <- nb2listw(nb_p1)
weights_p2 <- nb2listw(nb_p2)
weights_p3 <- nb2listw(nb_p3)



```


```{r}

moran_MME <- moran.test(summarized_main_data$MME, weights_p1)
moran_Prob2 <- moran.test(summarized_lasso_summer_predictions_p2$Prob, weights_p2)
moran_Prob3 <- moran.test(summarized_lasso_summer_predictions_p3$Prob, weights_p3)


moran_MME
moran_Prob2
moran_Prob3

```

